apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - nodePort: 30945
      port: 8080
      protocol: TCP
      targetPort: 8080
